project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "!ml-fundamentals/**"
    - "!ml-coding/**"
    - "!applied-ml/**"
    - "!ml-projects/**"

website:
  title: "Patrick Lowry"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: ML Fundamentals
        href: ml-fundamentals/
      - text: ML Coding
        href: ml-coding/
      - text: Applied ML
        href: applied-ml/
#      - text: My Projects
#        href: ml-projects/

format:
  html:
    theme: lux
    css: assets/css/custom-dark.css
    toc: true

execute:
  freeze: auto
  warning: false
  message: false
